name: fundl_app
description: Fundl App

publish_to: "none"

version: 1.0.4+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^2.1.0
  flutter_iconly: ^1.0.2
  flutter_svg: ^0.22.0
  marquee: ^2.2.0
  flutter_rating_bar: ^4.0.0
  motion_tab_bar_v2: ^0.2.4
  flutter_staggered_animations: ^1.0.0
  cached_network_image: ^3.1.0
  flutter_markdown: ^0.6.6

  # Coupons
  barcode_widget: ^2.0.1

  # Wheel
  flutter_fortune_wheel: ^1.1.0
  confetti: ^0.6.0

  # API
  dio: ^4.0.0
  flutter_secure_storage: ^4.2.1

  # State management
  redux: ^5.0.0
  flutter_redux: ^0.8.2

  # Serialization
  json_serializable: ^5.0.2
  build_runner: ^2.1.2

  # Other
  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.0.12
  android_intent_plus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/config/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
